use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[repr(u8)] pub enum Instructions {
	PerformScript = 1,
	SaveACopyAsXml = 3,
	GoToNextField = 4,
	GoToPreviousField = 5,
	GoToLayout = 6,
	NewRecordRequest = 7,
    DuplicateRecordRequest = 8,
	DeleteRecordRequest = 9,
	DeleteAllRecords = 10,
	InsertFromIndex = 11,
	InsertFromLastVisited = 12,
	InsertCurrentDate = 13,
	InsertCurrentTime = 14,
	GoToRecordRequestPage = 16,
	GoToField = 17,
	CheckSelection = 18,
	CheckRecord = 19,
	CheckFoundSet = 20,
	UnsortRecords = 21,
	EnterFindMode = 22,
	ShowAllRecords = 23,
	ModifyLastFind = 24,
	OmitRecord = 25,
	OmitMultipleRecords = 26,
	ShowOmmitedOnly = 27,
	PerformFind = 28,
	ShowHideToolbars = 29,
	ViewAs = 30,
	AdjustWindow = 31,
	OpenHelp = 32,
	OpenFile = 33,
	CloseFile = 34,
	ImportRecords = 35,
	ExportRecords = 36,
	SaveACopyAs = 37,
	OpenManageDatabase = 38,
	SortRecords = 39,
	RelookupFieldContents = 40,
	EnterPreviewMode = 41,
	PrintSetup = 42,
	Print = 43,
	ExitApplication = 44,
	UndoRedo = 45,
	Cut = 46,
	Copy = 47,
	Paste = 48,
	Clear = 49,
	SelectAll = 50,
	RevertRecordRequest = 51,
	EnterBrowserMode = 55,
	InsertPicture = 56,
	SendEvent = 57,
	InsertCurrentUserName = 60,
	InsertText = 61,
	PauseResumeScript = 62,
	SendMail = 63,
	SendDdeExecute = 64,
	DialPhone = 65,
	Speak = 66,
	PerformApplescript = 67,
	If = 68,
	Else = 69,
	EndIf = 70,
	Loop = 71,
	ExitLoopIf = 72,
	EndLoop = 73,
	GoToRelatedRecord = 74,
	CommitRecordsRequests = 75,
	SetField = 76,
	InsertCalculatedResult = 77,
	FreezeWindow = 79,
	RefreshWindow = 80,
	ScrollWindow = 81,
	NewFile = 82,
	ChangePassword = 83,
	SetMultiUser = 84,
	AllowUserAbort = 85,
	SetErrorCapture = 86,
	ShowCustomDialog = 87,
	OpenScriptWorkspace = 88,
	BlankLineComment = 89,
	HaltScript = 90,
	ReplaceFieldContents = 91,
	ShowHideTextRuler = 92,
	Beep = 93,
	SetUseSystemFormats = 94,
	RecoverFile = 95,
	SaveACopyAsAddOnPackage = 96,
	SetZoomLevel = 97,
	CopyAllRecordsRequests = 98,
	GoToPortalRow = 99,
	CopyRecordRequest = 101,
	FluchCacheToDisk = 102,
	ExitScript = 103,
	DeletePortalRow = 104,
	OpenPreferences = 105,
	CorrectWord = 106,
	SpellingOptions = 107,
	SelectDictionaries = 108,
	EditUserDictionary = 109,
	OpenUrl = 111,
	OpenManageValueLists = 112,
	OpenSharing = 113,
	OpenFileOptions = 114,
	AllowFormattingBar = 115,
	SetNextSerialValue = 116,
	ExecuteSql = 117,
	OpenHosts = 118,
	MoveResizeWindow = 119,
	ArrangeAllWindows = 120,
	CloseWindow = 121,
	NewWindow = 122,
	SelectWindow = 123,
	SetWindowTitle = 124,
	ElseIf = 125,
	ConstrainFoundSet = 126,
	ExtendFoundSet = 127,
	PerformFindReplace = 128,
	OpenFindReplace = 129,
	SetSelection = 130,
	InsertFile = 131,
	ExportFieldContents = 132,
	OpenRecordRequest = 133,
	AddAccount = 134,
	DeleteAccount = 135,
	ResetAccountPassword = 136,
	EnableAccount = 137,
	Relogin = 138,
	ConvertFile = 139,
	OpenManageDataSources = 140,
	SetVariable = 141,
	InstallMenuSet = 142,
	SaveRecordsAsExcel = 143,
	SaveRecordsAsPdf = 144,
	GoToObject = 145,
	SetWebViewer = 146,
	SetFieldByName = 147,
	InstallOntimerScript = 148,
	OpenEditSavedFinds = 149,
	PerformQuickFind = 150,
	OpenManageLayouts = 151,
	SaveRecordsAsSnapshotLink = 152,
	SortRecordsByField = 154,
	FindMatchingRecords = 155,
	ManageContainers = 156,
	InstallPluginFile = 157,
	InsertPdf = 158,
	InsertAudioVideo = 159,
	InsertFromUrl = 160,
	InsertFromDevice = 161,
	PerformScriptOnServer = 164,
	OpenManageThemes = 165,
	ShowHideMenubar = 166,
	RefreshObject = 167,
	SetLayoutObjectAnimation = 168,
	ClosePopover = 169,
	OpenUploadToHost = 172,
	EnableTouchKeyboard = 174,
	PerformJavascriptInWebViewer = 175,
    CommentedOut = 176,
	AvplayerPlay = 177,
	AvplayerSetPlaybackState = 178,
	AvplayerSetOptions = 179,
	RefreshPortal = 180,
	GetFolderPath = 181,
	TruncateTable = 182,
	OpenFavorites = 183,
	ConfigureRegionMonitorScript = 185,
	ConfigureLocalNotification = 187,
	GetFileExists = 188,
	GetFileSize = 189,
	CreateDataFile = 190,
	OpenDataFile = 191,
	WriteToDataFile = 192,
	ReadFromDataFile = 193,
	GetDataFilePosition = 194,
	SetDataFilePosition = 195,
	CloseDataFile = 196,
	DeleteFile = 197,
	RenameFile = 199,
	SetErrorLogging = 200,
	ConfigureNfcReading = 201,
	ConfigureMachineLearningModel = 202,
	ExecuteFilemakerDataApi = 203,
	OpenTransaction = 205,
	CommitTransaction = 206,
	RevertTransaction = 207,
	SetSessionIdentifier = 208,
	SetDictionary = 209,
	PerformScriptOnServerWithCallback = 210,
	TriggerClarisConnectFlow = 211,
}

pub static INSTRUCTIONMAP : [Option<Instructions>; 212] = [
    None,
	Some(Instructions::PerformScript),
    None,
	Some(Instructions::SaveACopyAsXml),
	Some(Instructions::GoToNextField),
	Some(Instructions::GoToPreviousField),
	Some(Instructions::GoToLayout),
	Some(Instructions::NewRecordRequest),
    Some(Instructions::DuplicateRecordRequest),
	Some(Instructions::DeleteRecordRequest),
	Some(Instructions::DeleteAllRecords),
	Some(Instructions::InsertFromIndex),
	Some(Instructions::InsertFromLastVisited),
	Some(Instructions::InsertCurrentDate),
	Some(Instructions::InsertCurrentTime),
    None,
	Some(Instructions::GoToRecordRequestPage),
	Some(Instructions::GoToField),
	Some(Instructions::CheckSelection),
	Some(Instructions::CheckRecord),
	Some(Instructions::CheckFoundSet),
	Some(Instructions::UnsortRecords),
	Some(Instructions::EnterFindMode),
	Some(Instructions::ShowAllRecords),
	Some(Instructions::ModifyLastFind),
	Some(Instructions::OmitRecord),
	Some(Instructions::OmitMultipleRecords),
	Some(Instructions::ShowOmmitedOnly),
	Some(Instructions::PerformFind),
	Some(Instructions::ShowHideToolbars),
	Some(Instructions::ViewAs),
	Some(Instructions::AdjustWindow),
	Some(Instructions::OpenHelp),
	Some(Instructions::OpenFile),
	Some(Instructions::CloseFile),
	Some(Instructions::ImportRecords),
	Some(Instructions::ExportRecords),
	Some(Instructions::SaveACopyAs),
	Some(Instructions::OpenManageDatabase),
	Some(Instructions::SortRecords),
	Some(Instructions::RelookupFieldContents),
	Some(Instructions::EnterPreviewMode),
	Some(Instructions::PrintSetup),
	Some(Instructions::Print),
	Some(Instructions::ExitApplication),
	Some(Instructions::UndoRedo),
	Some(Instructions::Cut),
	Some(Instructions::Copy),
	Some(Instructions::Paste),
	Some(Instructions::Clear),
	Some(Instructions::SelectAll),
	Some(Instructions::RevertRecordRequest),
    None,
    None,
    None,
	Some(Instructions::EnterBrowserMode),
	Some(Instructions::InsertPicture),
	Some(Instructions::SendEvent),
    None,
    None,
	Some(Instructions::InsertCurrentUserName),
	Some(Instructions::InsertText),
	Some(Instructions::PauseResumeScript),
	Some(Instructions::SendMail),
	Some(Instructions::SendDdeExecute),
	Some(Instructions::DialPhone),
	Some(Instructions::Speak),
	Some(Instructions::PerformApplescript),
	Some(Instructions::If),
	Some(Instructions::Else),
	Some(Instructions::EndIf),
	Some(Instructions::Loop),
	Some(Instructions::ExitLoopIf),
	Some(Instructions::EndLoop),
	Some(Instructions::GoToRelatedRecord),
	Some(Instructions::CommitRecordsRequests),
	Some(Instructions::SetField),
	Some(Instructions::InsertCalculatedResult),
    None,
	Some(Instructions::FreezeWindow),
	Some(Instructions::RefreshWindow),
	Some(Instructions::ScrollWindow),
	Some(Instructions::NewFile),
	Some(Instructions::ChangePassword),
	Some(Instructions::SetMultiUser),
	Some(Instructions::AllowUserAbort),
	Some(Instructions::SetErrorCapture),
	Some(Instructions::ShowCustomDialog),
	Some(Instructions::OpenScriptWorkspace),
	Some(Instructions::BlankLineComment),
	Some(Instructions::HaltScript),
	Some(Instructions::ReplaceFieldContents),
	Some(Instructions::ShowHideTextRuler),
	Some(Instructions::Beep),
	Some(Instructions::SetUseSystemFormats),
	Some(Instructions::RecoverFile),
	Some(Instructions::SaveACopyAsAddOnPackage),
	Some(Instructions::SetZoomLevel),
	Some(Instructions::CopyAllRecordsRequests),
	Some(Instructions::GoToPortalRow),
    None,
	Some(Instructions::CopyRecordRequest),
	Some(Instructions::FluchCacheToDisk),
	Some(Instructions::ExitScript),
	Some(Instructions::DeletePortalRow),
	Some(Instructions::OpenPreferences),
	Some(Instructions::CorrectWord),
	Some(Instructions::SpellingOptions),
	Some(Instructions::SelectDictionaries),
	Some(Instructions::EditUserDictionary),
    None,
	Some(Instructions::OpenUrl),
	Some(Instructions::OpenManageValueLists),
	Some(Instructions::OpenSharing),
	Some(Instructions::OpenFileOptions),
	Some(Instructions::AllowFormattingBar),
	Some(Instructions::SetNextSerialValue),
	Some(Instructions::ExecuteSql),
	Some(Instructions::OpenHosts),
	Some(Instructions::MoveResizeWindow),
	Some(Instructions::ArrangeAllWindows),
	Some(Instructions::CloseWindow),
	Some(Instructions::NewWindow),
	Some(Instructions::SelectWindow),
	Some(Instructions::SetWindowTitle),
	Some(Instructions::ElseIf),
	Some(Instructions::ConstrainFoundSet),
	Some(Instructions::ExtendFoundSet),
	Some(Instructions::PerformFindReplace),
	Some(Instructions::OpenFindReplace),
	Some(Instructions::SetSelection),
	Some(Instructions::InsertFile),
	Some(Instructions::ExportFieldContents),
	Some(Instructions::OpenRecordRequest),
	Some(Instructions::AddAccount),
	Some(Instructions::DeleteAccount),
	Some(Instructions::ResetAccountPassword),
	Some(Instructions::EnableAccount),
	Some(Instructions::Relogin),
	Some(Instructions::ConvertFile),
	Some(Instructions::OpenManageDataSources),
	Some(Instructions::SetVariable),
	Some(Instructions::InstallMenuSet),
	Some(Instructions::SaveRecordsAsExcel),
	Some(Instructions::SaveRecordsAsPdf),
	Some(Instructions::GoToObject),
	Some(Instructions::SetWebViewer),
	Some(Instructions::SetFieldByName),
	Some(Instructions::InstallOntimerScript),
	Some(Instructions::OpenEditSavedFinds),
	Some(Instructions::PerformQuickFind),
	Some(Instructions::OpenManageLayouts),
	Some(Instructions::SaveRecordsAsSnapshotLink),
    None,
	Some(Instructions::SortRecordsByField),
	Some(Instructions::FindMatchingRecords),
	Some(Instructions::ManageContainers),
	Some(Instructions::InstallPluginFile),
	Some(Instructions::InsertPdf),
	Some(Instructions::InsertAudioVideo),
	Some(Instructions::InsertFromUrl),
	Some(Instructions::InsertFromDevice),
    None,
    None,
	Some(Instructions::PerformScriptOnServer),
	Some(Instructions::OpenManageThemes),
	Some(Instructions::ShowHideMenubar),
	Some(Instructions::RefreshObject),
	Some(Instructions::SetLayoutObjectAnimation),
	Some(Instructions::ClosePopover),
    None,
    None,
	Some(Instructions::OpenUploadToHost),
    None,
	Some(Instructions::EnableTouchKeyboard),
	Some(Instructions::PerformJavascriptInWebViewer),
    Some(Instructions::CommentedOut),
	Some(Instructions::AvplayerPlay),
	Some(Instructions::AvplayerSetPlaybackState),
	Some(Instructions::AvplayerSetOptions),
	Some(Instructions::RefreshPortal),
	Some(Instructions::GetFolderPath),
	Some(Instructions::TruncateTable),
	Some(Instructions::OpenFavorites),
    None,
	Some(Instructions::ConfigureRegionMonitorScript),
    None,
	Some(Instructions::ConfigureLocalNotification),
	Some(Instructions::GetFileExists),
	Some(Instructions::GetFileSize),
	Some(Instructions::CreateDataFile),
	Some(Instructions::OpenDataFile),
	Some(Instructions::WriteToDataFile),
	Some(Instructions::ReadFromDataFile),
	Some(Instructions::GetDataFilePosition),
	Some(Instructions::SetDataFilePosition),
	Some(Instructions::CloseDataFile),
	Some(Instructions::DeleteFile),
    None,
	Some(Instructions::RenameFile),
	Some(Instructions::SetErrorLogging),
	Some(Instructions::ConfigureNfcReading),
	Some(Instructions::ConfigureMachineLearningModel),
	Some(Instructions::ExecuteFilemakerDataApi),
    None,
	Some(Instructions::OpenTransaction),
	Some(Instructions::CommitTransaction),
	Some(Instructions::RevertTransaction),
	Some(Instructions::SetSessionIdentifier),
	Some(Instructions::SetDictionary),
	Some(Instructions::PerformScriptOnServerWithCallback),
	Some(Instructions::TriggerClarisConnectFlow),
];

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Instruction {
    pub opcode: Instructions,
    pub switches: Vec<String>,
}

pub struct Script {
    pub script_name: String,
    pub instructions: Vec<Instruction>,
}


